CREATE TABLE IF NOT EXISTS CUSTOMER (
    id INTEGER AUTO_INCREMENT  PRIMARY KEY,
	custid VARCHAR(250) NOT NULL,
    fname VARCHAR(250) NOT NULL,
    lname VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    mobile VARCHAR(250) NOT NULL,
    status VARCHAR(250) NOT NULL,
    category VARCHAR(250) NOT NULL
);
